### ISSUE TITLE
Error run example

### ISSUE THREAD

**Issue by rodriguesfas** [KryQ/node-huidu-sdk#4]
Hello!
When running the example I am getting the following error:
(Can you help me with this problem?)

```bash
~/Workspace/node-huidu-sdk/dist/example$ node index.js 
[ '0 - 192.168.6.1:10001' ]
info: Card name: undefined {"service":"huidu-sdk","timestamp":"2023-08-06 08:47:42"}
0 - Change device
1 - Get Brightness
2 - Set Brightness
3 - List file
4 - Delete file
5 - Upload file
6 - Start video program
7 - Start parking program
8 - Set ETH to DHCP
9 - Set Device Name
10 - Get Device Name
11 - Get Device Info
12 - Get Programs
13 - Set Boot Logo
14 - Reload all fonts
15 - Realtime Update
16 - Turn off (display)
17 - Turn on (display)
99 - Disconnect
Please select desired option:  info: TCP ver: 16777222 {"service":"huidu-sdk","timestamp":"2023-08-06 08:47:42"}
info: GUID: eab3ee154f871808840995b17058306c {"service":"huidu-sdk","timestamp":"2023-08-06 08:47:42"}
file:///home/fasr/Workspace/node-huidu-sdk/dist/DisplayDevice.js:93
                        throw new Error(e_1);
                              ^

Error: [object Object]
    at DisplayDevice.<anonymous> (file:///home/fasr/Workspace/node-huidu-sdk/dist/DisplayDevice.js:93:31)
    at step (file:///home/fasr/Workspace/node-huidu-sdk/dist/DisplayDevice.js:47:23)
    at Object.throw (file:///home/fasr/Workspace/node-huidu-sdk/dist/DisplayDevice.js:28:53)
    at rejected (file:///home/fasr/Workspace/node-huidu-sdk/dist/DisplayDevice.js:20:65)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v19.0.1```

**Comment by fatihalp** [comment]
have you fixed? @rodriguesfas
